[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = { version = "0.2.1", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"